### ISSUE TITLE
Requested topics

### ISSUE THREAD

**Issue by ssnio** [BCCN-Prog/2019_day2#1]
Hi,

we would appreciate it if you could cover the following topics:
- Multiprocessing
- Docker and containers
- data base handling
- pipelines and design processes

Thank you.

**Comment by DorotheaMueller** [comment]
- optimization (how to combine C and Python efficiently)
- design patterns for data handling/processing

**Comment by marcbue** [comment]
Debugging (maybe in Pycharm)
